# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/C64258A/repos/Hestia-Game-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/C64258A/repos/Hestia-Game-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/C64258A/repos/Hestia-Game-Engine/CMakeFiles /Users/C64258A/repos/Hestia-Game-Engine/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/C64258A/repos/Hestia-Game-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine.app

# Build rule for target.
engine.app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine.app
.PHONY : engine.app

# fast build rule for target.
engine.app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/build
.PHONY : engine.app/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f depends/glfw/CMakeFiles/uninstall.dir/build.make depends/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f depends/glfw/src/CMakeFiles/glfw.dir/build.make depends/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/framework/Engine.o: src/framework/Engine.cpp.o

.PHONY : src/framework/Engine.o

# target to build an object file
src/framework/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/Engine.cpp.o
.PHONY : src/framework/Engine.cpp.o

src/framework/Engine.i: src/framework/Engine.cpp.i

.PHONY : src/framework/Engine.i

# target to preprocess a source file
src/framework/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/Engine.cpp.i
.PHONY : src/framework/Engine.cpp.i

src/framework/Engine.s: src/framework/Engine.cpp.s

.PHONY : src/framework/Engine.s

# target to generate assembly for a file
src/framework/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/Engine.cpp.s
.PHONY : src/framework/Engine.cpp.s

src/framework/GameEnvironment.o: src/framework/GameEnvironment.cpp.o

.PHONY : src/framework/GameEnvironment.o

# target to build an object file
src/framework/GameEnvironment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/GameEnvironment.cpp.o
.PHONY : src/framework/GameEnvironment.cpp.o

src/framework/GameEnvironment.i: src/framework/GameEnvironment.cpp.i

.PHONY : src/framework/GameEnvironment.i

# target to preprocess a source file
src/framework/GameEnvironment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/GameEnvironment.cpp.i
.PHONY : src/framework/GameEnvironment.cpp.i

src/framework/GameEnvironment.s: src/framework/GameEnvironment.cpp.s

.PHONY : src/framework/GameEnvironment.s

# target to generate assembly for a file
src/framework/GameEnvironment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/GameEnvironment.cpp.s
.PHONY : src/framework/GameEnvironment.cpp.s

src/framework/InputController.o: src/framework/InputController.cpp.o

.PHONY : src/framework/InputController.o

# target to build an object file
src/framework/InputController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/InputController.cpp.o
.PHONY : src/framework/InputController.cpp.o

src/framework/InputController.i: src/framework/InputController.cpp.i

.PHONY : src/framework/InputController.i

# target to preprocess a source file
src/framework/InputController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/InputController.cpp.i
.PHONY : src/framework/InputController.cpp.i

src/framework/InputController.s: src/framework/InputController.cpp.s

.PHONY : src/framework/InputController.s

# target to generate assembly for a file
src/framework/InputController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/InputController.cpp.s
.PHONY : src/framework/InputController.cpp.s

src/framework/ecs/Object.o: src/framework/ecs/Object.cpp.o

.PHONY : src/framework/ecs/Object.o

# target to build an object file
src/framework/ecs/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/Object.cpp.o
.PHONY : src/framework/ecs/Object.cpp.o

src/framework/ecs/Object.i: src/framework/ecs/Object.cpp.i

.PHONY : src/framework/ecs/Object.i

# target to preprocess a source file
src/framework/ecs/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/Object.cpp.i
.PHONY : src/framework/ecs/Object.cpp.i

src/framework/ecs/Object.s: src/framework/ecs/Object.cpp.s

.PHONY : src/framework/ecs/Object.s

# target to generate assembly for a file
src/framework/ecs/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/Object.cpp.s
.PHONY : src/framework/ecs/Object.cpp.s

src/framework/ecs/ObjectManager.o: src/framework/ecs/ObjectManager.cpp.o

.PHONY : src/framework/ecs/ObjectManager.o

# target to build an object file
src/framework/ecs/ObjectManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/ObjectManager.cpp.o
.PHONY : src/framework/ecs/ObjectManager.cpp.o

src/framework/ecs/ObjectManager.i: src/framework/ecs/ObjectManager.cpp.i

.PHONY : src/framework/ecs/ObjectManager.i

# target to preprocess a source file
src/framework/ecs/ObjectManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/ObjectManager.cpp.i
.PHONY : src/framework/ecs/ObjectManager.cpp.i

src/framework/ecs/ObjectManager.s: src/framework/ecs/ObjectManager.cpp.s

.PHONY : src/framework/ecs/ObjectManager.s

# target to generate assembly for a file
src/framework/ecs/ObjectManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/ecs/ObjectManager.cpp.s
.PHONY : src/framework/ecs/ObjectManager.cpp.s

src/framework/graphics/GraphicsComponent.o: src/framework/graphics/GraphicsComponent.cpp.o

.PHONY : src/framework/graphics/GraphicsComponent.o

# target to build an object file
src/framework/graphics/GraphicsComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsComponent.cpp.o
.PHONY : src/framework/graphics/GraphicsComponent.cpp.o

src/framework/graphics/GraphicsComponent.i: src/framework/graphics/GraphicsComponent.cpp.i

.PHONY : src/framework/graphics/GraphicsComponent.i

# target to preprocess a source file
src/framework/graphics/GraphicsComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsComponent.cpp.i
.PHONY : src/framework/graphics/GraphicsComponent.cpp.i

src/framework/graphics/GraphicsComponent.s: src/framework/graphics/GraphicsComponent.cpp.s

.PHONY : src/framework/graphics/GraphicsComponent.s

# target to generate assembly for a file
src/framework/graphics/GraphicsComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsComponent.cpp.s
.PHONY : src/framework/graphics/GraphicsComponent.cpp.s

src/framework/graphics/GraphicsSystem.o: src/framework/graphics/GraphicsSystem.cpp.o

.PHONY : src/framework/graphics/GraphicsSystem.o

# target to build an object file
src/framework/graphics/GraphicsSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsSystem.cpp.o
.PHONY : src/framework/graphics/GraphicsSystem.cpp.o

src/framework/graphics/GraphicsSystem.i: src/framework/graphics/GraphicsSystem.cpp.i

.PHONY : src/framework/graphics/GraphicsSystem.i

# target to preprocess a source file
src/framework/graphics/GraphicsSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsSystem.cpp.i
.PHONY : src/framework/graphics/GraphicsSystem.cpp.i

src/framework/graphics/GraphicsSystem.s: src/framework/graphics/GraphicsSystem.cpp.s

.PHONY : src/framework/graphics/GraphicsSystem.s

# target to generate assembly for a file
src/framework/graphics/GraphicsSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/GraphicsSystem.cpp.s
.PHONY : src/framework/graphics/GraphicsSystem.cpp.s

src/framework/graphics/SpriteComponent.o: src/framework/graphics/SpriteComponent.cpp.o

.PHONY : src/framework/graphics/SpriteComponent.o

# target to build an object file
src/framework/graphics/SpriteComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteComponent.cpp.o
.PHONY : src/framework/graphics/SpriteComponent.cpp.o

src/framework/graphics/SpriteComponent.i: src/framework/graphics/SpriteComponent.cpp.i

.PHONY : src/framework/graphics/SpriteComponent.i

# target to preprocess a source file
src/framework/graphics/SpriteComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteComponent.cpp.i
.PHONY : src/framework/graphics/SpriteComponent.cpp.i

src/framework/graphics/SpriteComponent.s: src/framework/graphics/SpriteComponent.cpp.s

.PHONY : src/framework/graphics/SpriteComponent.s

# target to generate assembly for a file
src/framework/graphics/SpriteComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteComponent.cpp.s
.PHONY : src/framework/graphics/SpriteComponent.cpp.s

src/framework/graphics/SpriteSystem.o: src/framework/graphics/SpriteSystem.cpp.o

.PHONY : src/framework/graphics/SpriteSystem.o

# target to build an object file
src/framework/graphics/SpriteSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteSystem.cpp.o
.PHONY : src/framework/graphics/SpriteSystem.cpp.o

src/framework/graphics/SpriteSystem.i: src/framework/graphics/SpriteSystem.cpp.i

.PHONY : src/framework/graphics/SpriteSystem.i

# target to preprocess a source file
src/framework/graphics/SpriteSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteSystem.cpp.i
.PHONY : src/framework/graphics/SpriteSystem.cpp.i

src/framework/graphics/SpriteSystem.s: src/framework/graphics/SpriteSystem.cpp.s

.PHONY : src/framework/graphics/SpriteSystem.s

# target to generate assembly for a file
src/framework/graphics/SpriteSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/graphics/SpriteSystem.cpp.s
.PHONY : src/framework/graphics/SpriteSystem.cpp.s

src/framework/tick/TickComponent.o: src/framework/tick/TickComponent.cpp.o

.PHONY : src/framework/tick/TickComponent.o

# target to build an object file
src/framework/tick/TickComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickComponent.cpp.o
.PHONY : src/framework/tick/TickComponent.cpp.o

src/framework/tick/TickComponent.i: src/framework/tick/TickComponent.cpp.i

.PHONY : src/framework/tick/TickComponent.i

# target to preprocess a source file
src/framework/tick/TickComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickComponent.cpp.i
.PHONY : src/framework/tick/TickComponent.cpp.i

src/framework/tick/TickComponent.s: src/framework/tick/TickComponent.cpp.s

.PHONY : src/framework/tick/TickComponent.s

# target to generate assembly for a file
src/framework/tick/TickComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickComponent.cpp.s
.PHONY : src/framework/tick/TickComponent.cpp.s

src/framework/tick/TickSystem.o: src/framework/tick/TickSystem.cpp.o

.PHONY : src/framework/tick/TickSystem.o

# target to build an object file
src/framework/tick/TickSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickSystem.cpp.o
.PHONY : src/framework/tick/TickSystem.cpp.o

src/framework/tick/TickSystem.i: src/framework/tick/TickSystem.cpp.i

.PHONY : src/framework/tick/TickSystem.i

# target to preprocess a source file
src/framework/tick/TickSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickSystem.cpp.i
.PHONY : src/framework/tick/TickSystem.cpp.i

src/framework/tick/TickSystem.s: src/framework/tick/TickSystem.cpp.s

.PHONY : src/framework/tick/TickSystem.s

# target to generate assembly for a file
src/framework/tick/TickSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/framework/tick/TickSystem.cpp.s
.PHONY : src/framework/tick/TickSystem.cpp.s

src/graphics/OpenGlModule.o: src/graphics/OpenGlModule.cpp.o

.PHONY : src/graphics/OpenGlModule.o

# target to build an object file
src/graphics/OpenGlModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/OpenGlModule.cpp.o
.PHONY : src/graphics/OpenGlModule.cpp.o

src/graphics/OpenGlModule.i: src/graphics/OpenGlModule.cpp.i

.PHONY : src/graphics/OpenGlModule.i

# target to preprocess a source file
src/graphics/OpenGlModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/OpenGlModule.cpp.i
.PHONY : src/graphics/OpenGlModule.cpp.i

src/graphics/OpenGlModule.s: src/graphics/OpenGlModule.cpp.s

.PHONY : src/graphics/OpenGlModule.s

# target to generate assembly for a file
src/graphics/OpenGlModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/OpenGlModule.cpp.s
.PHONY : src/graphics/OpenGlModule.cpp.s

src/graphics/Shader.o: src/graphics/Shader.cpp.o

.PHONY : src/graphics/Shader.o

# target to build an object file
src/graphics/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/Shader.cpp.o
.PHONY : src/graphics/Shader.cpp.o

src/graphics/Shader.i: src/graphics/Shader.cpp.i

.PHONY : src/graphics/Shader.i

# target to preprocess a source file
src/graphics/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/Shader.cpp.i
.PHONY : src/graphics/Shader.cpp.i

src/graphics/Shader.s: src/graphics/Shader.cpp.s

.PHONY : src/graphics/Shader.s

# target to generate assembly for a file
src/graphics/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/Shader.cpp.s
.PHONY : src/graphics/Shader.cpp.s

src/graphics/glad/glad.o: src/graphics/glad/glad.c.o

.PHONY : src/graphics/glad/glad.o

# target to build an object file
src/graphics/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/glad/glad.c.o
.PHONY : src/graphics/glad/glad.c.o

src/graphics/glad/glad.i: src/graphics/glad/glad.c.i

.PHONY : src/graphics/glad/glad.i

# target to preprocess a source file
src/graphics/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/glad/glad.c.i
.PHONY : src/graphics/glad/glad.c.i

src/graphics/glad/glad.s: src/graphics/glad/glad.c.s

.PHONY : src/graphics/glad/glad.s

# target to generate assembly for a file
src/graphics/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/graphics/glad/glad.c.s
.PHONY : src/graphics/glad/glad.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sample/SampleComponent.o: src/sample/SampleComponent.cpp.o

.PHONY : src/sample/SampleComponent.o

# target to build an object file
src/sample/SampleComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/sample/SampleComponent.cpp.o
.PHONY : src/sample/SampleComponent.cpp.o

src/sample/SampleComponent.i: src/sample/SampleComponent.cpp.i

.PHONY : src/sample/SampleComponent.i

# target to preprocess a source file
src/sample/SampleComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/sample/SampleComponent.cpp.i
.PHONY : src/sample/SampleComponent.cpp.i

src/sample/SampleComponent.s: src/sample/SampleComponent.cpp.s

.PHONY : src/sample/SampleComponent.s

# target to generate assembly for a file
src/sample/SampleComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.app.dir/build.make CMakeFiles/engine.app.dir/src/sample/SampleComponent.cpp.s
.PHONY : src/sample/SampleComponent.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... engine.app"
	@echo "... glfw"
	@echo "... src/framework/Engine.o"
	@echo "... src/framework/Engine.i"
	@echo "... src/framework/Engine.s"
	@echo "... src/framework/GameEnvironment.o"
	@echo "... src/framework/GameEnvironment.i"
	@echo "... src/framework/GameEnvironment.s"
	@echo "... src/framework/InputController.o"
	@echo "... src/framework/InputController.i"
	@echo "... src/framework/InputController.s"
	@echo "... src/framework/ecs/Object.o"
	@echo "... src/framework/ecs/Object.i"
	@echo "... src/framework/ecs/Object.s"
	@echo "... src/framework/ecs/ObjectManager.o"
	@echo "... src/framework/ecs/ObjectManager.i"
	@echo "... src/framework/ecs/ObjectManager.s"
	@echo "... src/framework/graphics/GraphicsComponent.o"
	@echo "... src/framework/graphics/GraphicsComponent.i"
	@echo "... src/framework/graphics/GraphicsComponent.s"
	@echo "... src/framework/graphics/GraphicsSystem.o"
	@echo "... src/framework/graphics/GraphicsSystem.i"
	@echo "... src/framework/graphics/GraphicsSystem.s"
	@echo "... src/framework/graphics/SpriteComponent.o"
	@echo "... src/framework/graphics/SpriteComponent.i"
	@echo "... src/framework/graphics/SpriteComponent.s"
	@echo "... src/framework/graphics/SpriteSystem.o"
	@echo "... src/framework/graphics/SpriteSystem.i"
	@echo "... src/framework/graphics/SpriteSystem.s"
	@echo "... src/framework/tick/TickComponent.o"
	@echo "... src/framework/tick/TickComponent.i"
	@echo "... src/framework/tick/TickComponent.s"
	@echo "... src/framework/tick/TickSystem.o"
	@echo "... src/framework/tick/TickSystem.i"
	@echo "... src/framework/tick/TickSystem.s"
	@echo "... src/graphics/OpenGlModule.o"
	@echo "... src/graphics/OpenGlModule.i"
	@echo "... src/graphics/OpenGlModule.s"
	@echo "... src/graphics/Shader.o"
	@echo "... src/graphics/Shader.i"
	@echo "... src/graphics/Shader.s"
	@echo "... src/graphics/glad/glad.o"
	@echo "... src/graphics/glad/glad.i"
	@echo "... src/graphics/glad/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sample/SampleComponent.o"
	@echo "... src/sample/SampleComponent.i"
	@echo "... src/sample/SampleComponent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

