//
// Created by David Price on 07/07/2020.
//

#ifndef HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_H
#define HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_H

class Event {
    int mId;
public:

};

#endif //HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_H
