//
// Created by David Price on 07/07/2020.
//

#ifndef HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_MANAGER_H
#define HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_MANAGER_H

class EventManager {

public:
    void getEventQueue() const;
};

#endif //HESTIA_GAME_ENGINE_INCLUDE_FRAMEWORK_EVENTS_EVENT_MANAGER_H